### ISSUE TITLE
openturns 1.9 pin

### ISSUE THREAD

**Issue by jschueller** [conda-forge/batman-feedstock#6]
Is there any reason to pin openturns 1.9?

**Comment by jschueller** [comment]
(bonus question: what about windows support?)

**Comment by tupui** [comment]
Yes, we still have some code that are not ported to OT1.10—[see your PR](https://gitlab.com/cerfacs/batman/merge_requests/31).

We do not support officially windows simply because we currently do not have the need to. Also, we do not have windows. (Although we could use some docker image for this). We are of course open to PR that will show windows support 😃

**Comment by tupui** [comment]
Closed in #7
